# Adapted from create-t3-app.

name: Release - Beta

on:
  pull_request:
    types: [labeled]
    branches:
      - main
jobs:
  prerelease:
    if: |
      github.repository_owner == 'shadcn-ui' &&
      contains(github.event.pull_request.labels.*.name, '🚀 autorelease')
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Use PNPM
        uses: step-security/action-setup@0ad50dc56a23060fa78b14cfcf0677c4e14b42bc # v5.0.0
        with:
          version: 9.0.6

      - name: Use Node.js 18
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Modify package.json version
        run: node .github/version-script-beta.js

      - name: Authenticate to NPM
        run: echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" >> packages/cli/.npmrc
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish Beta to NPM
        run: pnpm pub:beta

      - name: get-npm-version
        id: package-version
        uses: step-security/npm-get-version-action@109b96b9dd5542814198b15281ac486af476860f # v1.3.5
        with:
          path: packages/cli

      - name: Upload packaged artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: npm-package-shadcn-ui@${{ steps.package-version.outputs.current-version }}-pr-${{ github.event.number }} # encode the PR number into the artifact name
          path: packages/cli/dist/index.js
